package com.elftree.mall.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.elftree.mall.model.Region;
import com.elftree.mall.model.User;

import com.elftree.mall.greendao.RegionDao;
import com.elftree.mall.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig regionDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RegionDao regionDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        regionDaoConfig = daoConfigMap.get(RegionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        regionDao = new RegionDao(regionDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Region.class, regionDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        regionDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public RegionDao getRegionDao() {
        return regionDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
