package com.elftree.mall.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.elftree.mall.model.Region;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REGION".
*/
public class RegionDao extends AbstractDao<Region, Long> {

    public static final String TABLENAME = "REGION";

    /**
     * Properties of entity Region.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Region_id = new Property(1, String.class, "region_id", false, "REGION_ID");
        public final static Property Parent_id = new Property(2, String.class, "parent_id", false, "PARENT_ID");
        public final static Property Region_name = new Property(3, String.class, "region_name", false, "REGION_NAME");
        public final static Property Region_type = new Property(4, String.class, "region_type", false, "REGION_TYPE");
        public final static Property Agency_id = new Property(5, String.class, "agency_id", false, "AGENCY_ID");
    }


    public RegionDao(DaoConfig config) {
        super(config);
    }
    
    public RegionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REGION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REGION_ID\" TEXT," + // 1: region_id
                "\"PARENT_ID\" TEXT," + // 2: parent_id
                "\"REGION_NAME\" TEXT," + // 3: region_name
                "\"REGION_TYPE\" TEXT," + // 4: region_type
                "\"AGENCY_ID\" TEXT);"); // 5: agency_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REGION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Region entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String region_id = entity.getRegion_id();
        if (region_id != null) {
            stmt.bindString(2, region_id);
        }
 
        String parent_id = entity.getParent_id();
        if (parent_id != null) {
            stmt.bindString(3, parent_id);
        }
 
        String region_name = entity.getRegion_name();
        if (region_name != null) {
            stmt.bindString(4, region_name);
        }
 
        String region_type = entity.getRegion_type();
        if (region_type != null) {
            stmt.bindString(5, region_type);
        }
 
        String agency_id = entity.getAgency_id();
        if (agency_id != null) {
            stmt.bindString(6, agency_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Region entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String region_id = entity.getRegion_id();
        if (region_id != null) {
            stmt.bindString(2, region_id);
        }
 
        String parent_id = entity.getParent_id();
        if (parent_id != null) {
            stmt.bindString(3, parent_id);
        }
 
        String region_name = entity.getRegion_name();
        if (region_name != null) {
            stmt.bindString(4, region_name);
        }
 
        String region_type = entity.getRegion_type();
        if (region_type != null) {
            stmt.bindString(5, region_type);
        }
 
        String agency_id = entity.getAgency_id();
        if (agency_id != null) {
            stmt.bindString(6, agency_id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Region readEntity(Cursor cursor, int offset) {
        Region entity = new Region( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // region_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // parent_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // region_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // region_type
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // agency_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Region entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRegion_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParent_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRegion_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRegion_type(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAgency_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Region entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Region entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Region entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
